import Head from 'next/head'
import { useState, useEffect } from 'react';
import styles from '@/styles/Home.module.css'
import Navbar from "@/components/globals/Navbar/Navbar";
import Header from "@/components/Header/Header";
import InfoGrid from "@/components/index/InfoGrid/InfoGrid";
import CityProximity from "@/components/index/CityProximity/CityProximity";
import Footer from "@/components/globals/Footer/Footer";

export default function Home() {
    const [modal, setModal] = useState(null);

    useEffect(() => {
        // Ajoutez un écouteur d'événements pour le défilement lorsque la modal est ouverte
        const handleScroll = (e) => {
            e.preventDefault();
        };

        if (modal) {
            document.body.style.overflow = 'hidden';
            document.addEventListener('scroll', handleScroll, { passive: false });
        } else {
            document.body.style.overflow = 'auto';
            document.removeEventListener('scroll', handleScroll);
        }

        // Nettoyez l'écouteur d'événements lors du démontage du composant
        return () => {
            document.removeEventListener('scroll', handleScroll);
        };
    }, [modal]);

    const openModal = (modal) => {
        setModal(modal);
    }

    const closeModal = () => {
        setModal(null);
    }

    return (
        <>
            <Head>
                <title>Hubert Eats | Livraison de repas et courses à domicile</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.main}`}>
                <Navbar />
                <Header openModalFn={openModal} closeModalFn={closeModal} />
                <InfoGrid />
                <CityProximity />
                <Footer />
                {modal}
            </main>
        </>
    )
}
